import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";
import Layout from "../components/Layouts/Layout";
import MyWork from "../components/MyWork";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <About />
        <MyWork />
      </Layout>
    </div>
  );
}
